### ISSUE TITLE
Extension crashes after unlocking 

### ISSUE THREAD

**Issue by Scotty-Trees** [maniacx/Bluetooth-Battery-Meter#13]
Greetings and thank you for this great extension,

I'm using version 5 right now, and every time I lock my laptop and then unlock, the extension crashes. Here's the error it shows from Extension Manager. I am on Fedora 39 Gnome 45.3 on Wayland. Please let me know if you need any additional information. 

![Screenshot from 2024-01-20 17-17-27](https://github.com/maniacx/Bluetooth-Battery-Meter/assets/45135187/a0935277-2210-4eca-8664-2b533d040ea7)

My system info:
```# System Details Report
---

## Report details
- **Date generated:**                              2024-01-20 17:20:49

## Hardware Information:
- **Hardware Model:**                              Acer Aspire E5-576G
- **Memory:**                                      16.0 GiB
- **Processor:**                                   Intel® Core™ i5-8250U × 8
- **Graphics:**                                    Intel® UHD Graphics 620 (KBL GT2)
- **Graphics 1:**                                  NVIDIA GeForce MX150
- **Disk Capacity:**                               256.1 GB

## Software Information:
- **Firmware Version:**                            V1.32
- **OS Name:**                                     Fedora Linux 39 (Workstation Edition)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.3
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.6.11-200.fc39.x86_64
```

**Comment by maniacx** [comment]
Thank you for reporting this.
I have added checks this._desktopSettings.
Can you please test the updated version on Github?

**Comment by Scotty-Trees** [comment]
I'm sorry I didn't see any instructions here on how to manually install, so I downloaded the .zip file when you press the green Code button on your main page, I extracted it and moved the folder to my gnome-shell extensions folder where my other extensions are, logged out and back in, but I do not see the extension show up in Extension Manager. 

Is there a proper way to manually install your extension so I can test it? Appreciate the help, thank you.

**Comment by maniacx** [comment]
Yes. Run ./install.sh

* install gettext (it may already be installed but just run the command in terminal to be safe)
`sudo dnf install getttext`


* Extract downloaded zip,
*  open the folder.
*  Right click on filename `install.sh` and `Properties` > Enable `Executable as Program`
*  Right click on filename `install.sh` and click copy
* Open terminal and right click and paste (this will paste the path to install.sh) and hit Enter.
* Logout - Login and enable extension

**Comment by Scotty-Trees** [comment]
Thanks for the instructions. Perhaps maybe include that part of your ReadMe.md file for manually installations. I look at other extension GitHubs and all of them have very slight different way to do it.

I did what you suggested, downloaded, extracted, installed, logged out/in again and then tested it during lock/unlock and now everything is working good again, thank you for the quick fix. Glad it was a simple fix! You may close this issue at your earliest convenience.

**Comment by maniacx** [comment]
Great. Thank you for reporting. I will submit for a new version on Gnome extension website
