### ISSUE TITLE
Testing GNOME 42

### ISSUE THREAD

**Issue by alecalanis** [maniacx/Bluetooth-Battery-Meter#16]
First of all, i love this extension, thank you for providing it.

After reading that you created a backport for Gnome43-44, i wonder if you could create a backport for Gnome 42.9. This is the current version used in latest Ubuntu 22.04 LTS, which is, by far, the most used distribution and version around.
This would also enable me to use it on a few work-related notebooks :)

I tried to run that branch, but if fails, so i suppose its probably not compatible at all.

Thx

**Comment by maniacx** [comment]
@alecalanis  @ViBE-HU  
I have add a branch GNOME42-44 for testing. It supports GNOME42. Test it and give feedback. Thank you.

**Comment by maniacx** [comment]
Tested the extension myself by installing ubuntu 22.04.

**Comment by alecalanis** [comment]
@maniacx sorry for the late reply. Just re-installed and tested it on ubuntu v22.04.3 with gnome v42.9... and it works like a charm :+1: 
Thank you very much!
