### ISSUE TITLE
Had to also enable KernelExperimental in main.conf

### ISSUE THREAD

**Issue by kootepe** [maniacx/Bluetooth-Battery-Meter#24]
As per title,

Had to set both Experimental and KernelExperimental to true in /etc/bluetooth/main.conf to get this to work. 
On Debian Trixie.

**Comment by maniacx** [comment]
Oh. Thank for letting me know. I guess may be some Bluetooth device or distro needs it.i didn't know about it. I will update read me

**Comment by kootepe** [comment]
They both needed to be enabled, just Experimental or just KernelExperimental didn't work.

Thank you for the great plugin :+1:

**Comment by maniacx** [comment]
Thanks. I have added it to docs
