### ISSUE TITLE
[Suggestion] UPower backend?

### ISSUE THREAD

**Issue by gaussandhisgun** [maniacx/Bluetooth-Battery-Meter#25]
So, today I accidentally opened Gnome's power manager with my phones connected and was surprised to know that Gnome's settings report the charges of connected bluetooth devices - moreover, connected *phones*! I've never seen that done anywhere else, especially with a 2009 dumbphone. So I poked around for a bit and figured out that these devices are (*roughly*) reported by UPower. Seeing the charge of your phone over Bluetooth could be useful if you're not able to install KDE Connect on it. 

![изображение](https://github.com/maniacx/Bluetooth-Battery-Meter/assets/63512006/951fa4f2-6ae7-4574-8664-d79e3cddb62f)

P.S. Also, maybe, some kind of device class or MAC based blacklist would be useful for those who do *not* want to see said charge?

**Comment by maniacx** [comment]
Before I released this extension to the public, I did include phone, but it is a hit or miss. I tried 3 phone. 2 phones always report 100% and not the actual battery limit. So I didn't include phones. As probably a lot of users would have reported the extension is not working.

**Comment by gaussandhisgun** [comment]
but that would be a *upower* issue?

**Comment by maniacx** [comment]
@gaussandhisgun 

Can you install and test branch. It is compatible with gnome 45 and 46. 
If you are using gnome44 or older let me know i will create a test branch for older gnome.
This should show phone battery level as well.
https://github.com/maniacx/Bluetooth-Battery-Meter/tree/test
Install extension by running ./install.sh ,  logout and login and test the extension.

**Comment by gaussandhisgun** [comment]
it should, but does not
![изображение](https://github.com/maniacx/Bluetooth-Battery-Meter/assets/63512006/95ebcdfc-4212-45ca-a97f-a2969a252380)
headset functionality still works, no problems there

**Comment by maniacx** [comment]
Strange for me it works.
![Screenshot from 2024-04-16 23-53-19](https://github.com/maniacx/Bluetooth-Battery-Meter/assets/4295343/63846a10-5f7b-465d-a592-cbb0ac3ca5e3)

1. Did you log out and login after installtion?
2. Did you enable the settings in preferences?

![Screenshot from 2024-04-16 23-56-19](https://github.com/maniacx/Bluetooth-Battery-Meter/assets/4295343/97c59061-bfc3-45b5-99b0-0d2760ac04c7)

Let me know. Thanks

EDIT: If it still doesnt work could you post the output bluetoothctl info in terminal.

```
bluetoothctl info xx:xx:xx:xx:xx:xx
```
 xx:xx:xx:xx:xx:xx is your connected phone Mac address.

**Comment by gaussandhisgun** [comment]
huh, i *do not* have the setting shown on that screenshot 🤔 seems like a Gnome moment, hold up

**Comment by gaussandhisgun** [comment]
reinstalling the extension did make it work
![изображение](https://github.com/maniacx/Bluetooth-Battery-Meter/assets/63512006/077040bf-cff2-49e0-a0c9-ae324260404d)

**Comment by maniacx** [comment]
@gaussandhisgun 

Lol. Just noticed the name. Global failure. :)

Hey I have  add new features to the extension Would you be kinda enough to test it for a week?

It includes
1. Phone support.

2. Per Device battery reporting. check in extension prefs. 
- If any device is reporting incorrect battery level you can disable it from displaying battery level. in quicksetting and indicator
- If you can choose disable indicator for a device, but still show battery info in quick settings.


If there are any issues, report immediately, if there are no issues report after a week.

**Comment by maniacx** [comment]
Oops. Forgot to mention the branch to test.

https://github.com/maniacx/Bluetooth-Battery-Meter/tree/test-per-device

**Comment by maniacx** [comment]
Added feature
