### ISSUE TITLE
Add the battery percentage on the system tray 

### ISSUE THREAD

**Issue by ConstantMan** [maniacx/Bluetooth-Battery-Meter#27]
Basically what the title says it would be nice to have the option to see at a glance the battery percentage in numbers ,instead of having just an icon of the connected device with bullets indicating the percentage  and the full text percentage hidden in the gnome Bluetooth menu .
![image](https://github.com/maniacx/Bluetooth-Battery-Meter/assets/56481040/206ef416-8d82-4bbf-a008-a16625ecbc52)
![image](https://github.com/maniacx/Bluetooth-Battery-Meter/assets/56481040/5fb56d6e-d085-4684-b022-d29a93f5f5b9)

**Comment by maniacx** [comment]
You mean icon and numbers or only numbers.
The only reason I didn't add it cause it will take the whole task bar if we have 3-4 bluetooth devices, such as general most user would have atleaat 2 or 3 devices. keyboard, mouse, headphone.

I am a bit bus these days, but I will have a look at it when I have some free time.

**Comment by maniacx** [comment]
@ConstantMan 

Hey I have  an added new features to the extension. Would you be kinda enough to test it for a week?

It includes
1. Phone support.

2. Per Device battery reporting. check in extension prefs. 
- If any device is reporting incorrect battery level you can disable it from displaying battery level. in quicksetting and indicator
- If you can choose disable indicator for a device, but still show battery info in quick settings.

3. Added option to show battery level in text in the indicator


If there are any issues, report immediately, if there are no issues report after a week.

https://github.com/maniacx/Bluetooth-Battery-Meter/tree/test-per-device

**Comment by maniacx** [comment]
Added feature.
