### ISSUE TITLE
Not showing battery percentage

### ISSUE THREAD

**Issue by brianjmurrell** [maniacx/Bluetooth-Battery-Meter#30]
I have a Logitech mouse that this extension has in the past shown the battery level for.  It does not seem to be showing it any more.

I am using Fedora 40 which includes GNOME 46 and is fully up-to-date.

Here's what the Bluetooth quick-settings menu looks like currently:

![image](https://github.com/maniacx/Bluetooth-Battery-Meter/assets/559317/2099b62a-4202-4120-a29a-48139417dcb9)

It used to show the battery level for that exact same mouse.  It no longer does (obviously).

My extension settings:

![image](https://github.com/maniacx/Bluetooth-Battery-Meter/assets/559317/c96fc34e-006e-4836-a86a-0335c25e72b0)

Here's the About info for the extension:

![image](https://github.com/maniacx/Bluetooth-Battery-Meter/assets/559317/57ae3b4d-f841-49e1-9028-d7fc4dfaffce)

**Comment by maniacx** [comment]
Can you check and test if bluez experimental feature is enabled?

https://maniacx.github.io/Bluetooth-Battery-Meter/#enable-experimental-bluez

Also once you have enabled and verified experiment feature.

Note down the mac address of mouse and use the following command in terminal 

```
bluetoothctl info xx.xx.xx.xx.xx.xx
```
 xx.xx.xx.xx.xx.xx is the mac address of your mouse.

Let me know if you see the battery level in the output of this command.

Also check if the mouse battery level shows in gnome settings > power

![power.png](https://github.com/maniacx/Bluetooth-Battery-Meter/assets/4295343/f2c14e9c-524a-44e7-b811-db8fcaa83c21)

**Comment by brianjmurrell** [comment]
> Can you check and test if bluez experimental feature is enabled?
> 
> https://maniacx.github.io/Bluetooth-Battery-Meter/#enable-experimental-bluez

```
$ bluetoothctl show | grep -q 'PowerState' && echo 'Experimental flag enabled' || echo 'Experimental flag disabled'

Experimental flag enabled
```
 
> ```
> bluetoothctl info xx.xx.xx.xx.xx.xx
> ```

```
$ bluetoothctl info 34:88:5D:56:A8:C1
Device 34:88:5D:56:A8:C1 (public)
	Name: Bluetooth Mouse M557
	Alias: Bluetooth Mouse M557
	Class: 0x00000580 (1408)
	Icon: input-mouse
	Paired: yes
	Bonded: yes
	Trusted: yes
	Blocked: no
	Connected: yes
	WakeAllowed: yes
	LegacyPairing: no
	UUID: Service Discovery Serve.. (00001000-0000-1000-8000-00805f9b34fb)
	UUID: Human Interface Device... (00001124-0000-1000-8000-00805f9b34fb)
	UUID: PnP Information           (00001200-0000-1000-8000-00805f9b34fb)
	Modalias: usb:v046DpB010d1001
```

> Let me know if you see the battery level in the output of this command.

I don't see anything.

> 
> Also check if the mouse battery level shows in gnome settings > power

Nothing at all there about any devices:

![image](https://github.com/maniacx/Bluetooth-Battery-Meter/assets/559317/6c476e1f-4be2-45cc-aa57-ba1c9d35da81)

**Comment by maniacx** [comment]
Strange.
I have booted my Fedora and it does detect all device in Gnome Settings > Power

![image](https://github.com/maniacx/Bluetooth-Battery-Meter/assets/4295343/cd067e83-14b7-4cfd-ad08-942bd3c6cacc)

```
bluetoothctl info DE:27:1B:42:8C:9E
Device DE:27:1B:42:8C:9E (public)
	Name: ROG GLADIUS II WIRELESS
	Alias: ROG GLADIUS II WIRELESS
	Appearance: 0x03c2 (962)
	Icon: input-mouse
	Paired: yes
	Bonded: yes
	Trusted: yes
	Blocked: no
	Connected: yes
	WakeAllowed: no
	LegacyPairing: no
	UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
	UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
	UUID: Device Information        (0000180a-0000-1000-8000-00805f9b34fb)
	UUID: Battery Service           (0000180f-0000-1000-8000-00805f9b34fb)
	UUID: Human Interface Device    (00001812-0000-1000-8000-00805f9b34fb)
	Modalias: usb:v0B05p18C1d0236
	Battery Percentage: 0x64 (100)
```
And if the device detects in Gnome Settings > Power and it is shows battery information in bluetoothctl info, it will display in extension as well.

I had one user reporting that they had to enable Kernel Experimental to get this information on one of their devices.

You could try enabling it in `/etc/bluetooth/main.conf`

Find this line
```
# Enables kernel experimental features, alternatively a list of UUIDs
# can be given.
# Possible values: true,false,<UUID List>
# Possible UUIDS:
# d4992530-b9ec-469f-ab01-6c481c47da1c (BlueZ Experimental Debug)
# 671b10b5-42c0-4696-9227-eb28d1b049d6 (BlueZ Experimental Simultaneous Central and Peripheral)
# 15c0a148-c273-11ea-b3de-0242ac130004 (BlueZ Experimental LL privacy)
# 330859bc-7506-492d-9370-9a6f0614037f (BlueZ Experimental Bluetooth Quality Report)
# a6695ace-ee7f-4fb9-881a-5fac66c629af (BlueZ Experimental Offload Codecs)
# 6fbaf188-05e0-496a-9885-d6ddfdb4e03e (BlueZ Experimental ISO socket)
# 69518c4c-b69f-4679-8bc1-c021b47b5733 (BlueZ Experimental Poll Errqueue)
# Defaults to false.
#KernelExperimental = false
```

And remove the `#` from it and set it to true and save it
It should look like this.
```
# Enables kernel experimental features, alternatively a list of UUIDs
# can be given.
# Possible values: true,false,<UUID List>
# Possible UUIDS:
# d4992530-b9ec-469f-ab01-6c481c47da1c (BlueZ Experimental Debug)
# 671b10b5-42c0-4696-9227-eb28d1b049d6 (BlueZ Experimental Simultaneous Central and Peripheral)
# 15c0a148-c273-11ea-b3de-0242ac130004 (BlueZ Experimental LL privacy)
# 330859bc-7506-492d-9370-9a6f0614037f (BlueZ Experimental Bluetooth Quality Report)
# a6695ace-ee7f-4fb9-881a-5fac66c629af (BlueZ Experimental Offload Codecs)
# 6fbaf188-05e0-496a-9885-d6ddfdb4e03e (BlueZ Experimental ISO socket)
# 69518c4c-b69f-4679-8bc1-c021b47b5733 (BlueZ Experimental Poll Errqueue)
# Defaults to false.
KernelExperimental = true
```
then restart bluetooth.
```
systemctl restart bluetooth
```

Check if it displays.
If it still doesnt display.

Restart the PC and check again.

If it still doesnt work, Post your content of

`cat /etc/bluetooth/main.conf`

```
bluetoothctl version
bluetoothctl show
btmgmt info
btmgmt extinfo
btmgmt secinfo
btmgmt expinfo 
```
**Do note that kernel experiment are experimental features that can enable some extra features but can also have bluetooth related bugs. So be prepared  for instance if bluetooth stop working or disconnects mouse, you should have another way to navigate, such as using bluetooth mouse USB cable or trackpad if it a laptop**

**Comment by brianjmurrell** [comment]
> I had one user reporting that they had to enable Kernel Experimental to get this information on one of their devices.

This resolved it for me, all but the `bluetoothctl info` but I don't really care about that.

I do see the percentage in the quick-settings tile as well as in the GNOME Control Centre now.

Strange that I needed to do this now when this was all working in the past.

**Comment by maniacx** [comment]
Great. I forgot to update documentation when the user advice me to do so. I will update it when I have time. Thank you for testing and confirming.

**Comment by maniacx** [comment]
hello @brianjmurrell 

Hey I have  an updated. Would you be kinda enough to test it for a week?

It includes
1. Phone support.

2. Per Device battery reporting. check in extension prefs. 
- If any device is reporting incorrect battery level you can disable it from displaying battery level. in quicksetting and indicator
- If you can choose disable indicator for a device, but still show battery info in quick settings.

3. Added option to show battery level in text in the indicator 

If there are any issues, report immediately, if there are no issues report after a week.

**Comment by maniacx** [comment]
Oops. Forgot to mention the branch to test.

https://github.com/maniacx/Bluetooth-Battery-Meter/tree/test-per-device

**Comment by brianjmurrell** [comment]
[ Sorry to resurrect an edit, but you have my curious now ]

> Lol. Just noticed the name. Global failure. :)

Not quite following what this comment was referring to.

> Hey I have an updated. Would you be kinda enough to test it for a week?

Seems to be working at 2e82f9e.

**Comment by maniacx** [comment]
I apologize for that I was lazy and sleepy
I have added some new features to the extensio . But wanted feedback from several users. 

So I made my first post to another user and copy pasted the same post to you. 

I found it funny that name of mobile device was 'global failure'

https://github.com/maniacx/Bluetooth-Battery-Meter/issues/25#issuecomment-2060987318


New feature that I have added are,

1. When users have multiple device, User can disable, enable battery reporting or disable indicator only, for each devices incase the do no want to display battery level for some devices..

2. Added support to show battery level of connected  android phone and iPhone.

3. Added feature to display battery level in text, next to indicator.

If you have the time, you can install and test it.
Or if you do not wish to text, that is fine too.

**Comment by brianjmurrell** [comment]
I see.  I did install your test branch.  Seems to be working.
