### ISSUE TITLE
Duplicated  icons in QS

### ISSUE THREAD

**Issue by Bitals** [maniacx/Bluetooth-Battery-Meter#31]
All bluetooth devices are duplicated on the QuickSettings BT section:

![image](https://github.com/maniacx/Bluetooth-Battery-Meter/assets/11341915/d0f20284-ac07-4966-9dc0-0275837013da)

Gnome 46
ArchLinux

**Comment by Bitals** [comment]
UPD: I am dumb, this was the https://github.com/Extensions-Valhalla/gnome-bluetooth-quick-connect

(However I do prefer that extensions default themable toggles over a blue BT icon).

**Comment by maniacx** [comment]
Hmm. Strange. I tested this extension in Ubuntu it changes the icon color according to the accent color

The custom theme might not have an entry for 'shell-link' style class.
 I will check if there is a more commonly use stylesclass, so that it gets customized by the theme.

**Comment by Bitals** [comment]
@maniacx afaik Ubuntu uses their own Accent Color implementation, the `xdg-desktop`-compatible one was teased for Gnome 47 by upstream.

I use https://github.com/GradienceTeam/Gradience

P.S. I do also think toggles just look better, as there already is a BT icon in the section header, everything inside collapsible section has to be a BT device after all.

**Comment by maniacx** [comment]
@Bitals 

I have added support for custom themes.

But I am still using an icon as I prefer it over toggle switch. 
Toggle switch make the menu height much larger (at least on Vanilla Gnomes theme. adwaita) and also allocates more width and with the battery icon and text there is no much room left to display device name.

Would you mind testing it on your device, even if you are not interested in the extension. I just need some feedback if it works correctly.

 the latest version from Github. Download and run ./install.sh.
Note: You might have to install `gettext` before runnung ./install.sh.

https://github.com/maniacx/Bluetooth-Battery-Meter/tree/GNOME45

Thank you.

**Comment by Bitals** [comment]
@maniacx not to argue with any of your points, but Gradience is not a custom theme. It is just a third-party instrument to use Adwaita accent colors, because the colors themselves have been there for years, but tooling to control them through Gnome is still yet to arrive.
The "|" and "O" are standard Gnome stuff from the accessibility settings.

I will test shortly. I am interested in the extension as I want a battery meter more then toggles lol.

**Comment by Bitals** [comment]
@maniacx I confirm, very orange:
![image](https://github.com/maniacx/Bluetooth-Battery-Meter/assets/11341915/8e92a4c9-0f4d-426a-a01f-4b32c10219dc)
