### ISSUE TITLE
Battery percentage persists after disabling Bluetooth

### ISSUE THREAD

**Issue by arvindchauhan1** [maniacx/Bluetooth-Battery-Meter#33]
**Expected Behavior:**
When Bluetooth is disabled, the battery percentage for connected devices should no longer be displayed.

**Actual Behavior:**
After disabling Bluetooth, the battery percentage for previously connected devices remains displayed.

![Screenshot from 2024-06-29 08-59-51](https://github.com/maniacx/Bluetooth-Battery-Meter/assets/81680256/b0d75b22-1485-4617-990d-ea6d2f21480d)

![Screenshot from 2024-06-29 09-00-01](https://github.com/maniacx/Bluetooth-Battery-Meter/assets/81680256/2c9429c1-0a16-4a1e-9ea2-52171c4d3042)

**Operating System:** Fedora 40
**Desktop Environment:** Gnome 46

**Comment by maniacx** [comment]
Apologize. I was busy. I will have a look at it.

**Comment by maniacx** [comment]
@arvindchauhan1 
Thank for reporting this. Didn't realized it had more issue than I expected when introducing these new features.

Can you please test the latest updated branch and let me know if this fixes the issue.

https://github.com/maniacx/Bluetooth-Battery-Meter/tree/GNOME45

You might have to install gettext prior to installing extension from Github sources.

```
sudo dnf install gettext
```
download the latest sources from github and run ./install.sh
log out and relogin and test please.

**Comment by maniacx** [comment]
Bug solve. No response.
