### ISSUE TITLE
Port to GNOME 47

### ISSUE THREAD

**Issue by antrmn** [maniacx/Bluetooth-Battery-Meter#37]
GNOME 47.rc has been released, with the stable release set for September 18. Please update for GNOME 47 compatibility. The upgrade guide can be found here: [Port Extensions to GNOME Shell 47](https://gjs.guide/extensions/upgrading/gnome-shell-47.html)

Thanks!

**Comment by thenameisluk** [comment]
funny thing in the [manifest](https://github.com/maniacx/Bluetooth-Battery-Meter/blob/GNOME45/metadata.json) there are two shell 46 so that second 46 might be a typo (haven't tested it yet)
@maniacx is it?

**Comment by thenameisluk** [comment]
yep the externsion seams to work

@antrmn if you want to get it working, just update ```~/.local/share/gnome-shell/extensions/Bluetooth-Battery-Meter\@maniacx.github.com/metadata.json``` to this
```
{
  "_generated": "Generated by SweetTooth, do not edit",
  "description": "A Gnome extension featuring indicator icons in system tray, serving as meter for Bluetooth device battery levels and providing detailed battery levels via icon/text in the Bluetooth quick sett>
  "gettext-domain": "Bluetooth-Battery-Meter@maniacx.github.com",
  "name": "Bluetooth Battery Meter",
  "session-modes": [
    "unlock-dialog",
    "user"
  ],
  "settings-schema": "org.gnome.shell.extensions.Bluetooth-Battery-Meter",
  "shell-version": [
    "45",
    "46",
    "47"
  ],
  "url": "https://github.com/maniacx/Bluetooth-Battery-Meter",
  "uuid": "Bluetooth-Battery-Meter@maniacx.github.com",
  "version": 20
}
```

**Comment by maniacx** [comment]
Yes. it is typo. I will correct it tonight.

I did install Gnome47 (Fedora rawhide) yesterday and tested it and there are no changes needed with Gnome 47.
I was planning to add a feature, to sort bluetooth devices in quicksetting according to history. 
Connected devices list will appear on top and paired device list will appear at the bottom same default Gnome,
But instead of sorting by alphabethical alias order,  this will sort the connected devices and paired devices by connection history. i.e recently connected device will be on top of the list  and oldest connected will be on bottom of the list and the same for paired devices. However, last minute I found a bug when bluetooth adapter is disconnected it will lose all history. So need to debug and thoroughly  test this feature 

So for now, I will revert this feature and release without any changes. 
Thank you for bringing it to my notice.

**Comment by maniacx** [comment]
@antrmn 
@thenameisluk 

Thanks for notifying.
I have already released, and should be available on gnome-extension website.

Feel free to reopen this if there are any issues with the released version.

**Comment by maniacx** [comment]
@antrmn
@thenameisluk 

Hello everything. Would you be able to give some feedback on the new update pushed on github.

Feature are mentioned here
https://github.com/maniacx/Bluetooth-Battery-Meter/issues/39#issuecomment-2525442073

**Comment by thenameisluk** [comment]
@maniacx works if that's what you asked for and features are nice
there is some weird empty space (see image below)

but one thing i'd like added is displaying bluetooth devices that don't share battery level
it'd be nice to see that my mouse is connected without having to check manually
![image](https://github.com/user-attachments/assets/e069fece-26c3-4536-b2f1-8007f2a5c53f)

**Comment by thenameisluk** [comment]
@maniacx the white space is extending even more for some reason

![Zrzut ekranu z 2024-12-09 14-51-20](https://github.com/user-attachments/assets/87d718ae-9186-4462-bdae-352abc909411)

**Comment by maniacx** [comment]
> @maniacx the white space is extending even more for some reason
> 
> ![Zrzut ekranu z 2024-12-09 14-51-20](https://github.com/user-attachments/assets/87d718ae-9186-4462-bdae-352abc909411)
> 


Thank you. I will check what is the issue. What is your linux distro? Ubuntu 24.10?

**Comment by thenameisluk** [comment]
@maniacx yes 47

**Comment by maniacx** [comment]
@thenameisluk 
Check the latest commit, i pushed.
This should fix the added space issue that was caused when destroy is called.

> but one thing i'd like added is displaying bluetooth devices that don't share battery level
> it'd be nice to see that my mouse is connected without having to check manually

You mean show all connected devices icons on indicator (system tray)?  this populate the indicators, wouldn't it? Unless I add something like per device indicators.

**Comment by thenameisluk** [comment]
@maniacx i mean only bluetooth devices

i have a **bluetooth** mouse that doesn't share it's battery with my pc so it doesn't get displayed
but instead it'd be nice if it was just displayed without the battery indicatory, just an icon to see it's connected

![image](https://github.com/user-attachments/assets/f8292548-cd92-4c91-85b4-c3df884f2297)
like this ^

**Comment by thenameisluk** [comment]
> @thenameisluk 
> 
> Check the latest commit, i pushed.
> 
> This should fix the added space issue that was caused when destroy is called.

yep it fixed it

**Comment by maniacx** [comment]
@thenameisluk 

I have push an updaet and added those settings.
Any feedback post it here.
https://github.com/maniacx/Bluetooth-Battery-Meter/issues/39

Let continue our discussion here.
Thanks
