### ISSUE TITLE
100% battery percent text not displayed properly

### ISSUE THREAD

**Issue by ionutbortis** [maniacx/Bluetooth-Battery-Meter#9]
Hi and thank you for this extension!

I recently started to use Battery Health Charging and one article about the Bluetooth Battery Meter extension popped the other days. I was previously using the Bluetooth Quick Connect extension, which kinda does the same thing, but yours is more up to date and will probably be maintained for a longer time.

It seems, at least on my side, that I have a display issue when the device's battery is 100%. This happens with/without the Large Text accessibility feature.

With Large Text on:
![Screenshot from 2024-01-14 12-43-26](https://github.com/maniacx/Bluetooth-Battery-Meter/assets/5013697/8b657a43-9d50-419a-bc70-61bfbf5793f2)

With Large Text off:
![Screenshot from 2024-01-14 12-43-52](https://github.com/maniacx/Bluetooth-Battery-Meter/assets/5013697/9efc9fa5-b05c-40d4-9fc4-56d28b78b829)

I changed the css width to 2.6em, and it seems to work, but not sure if that's the proper fix:
```
.bbm-label-percentage {
  width: 2.6em;
}
```

Maybe different distros use different UI fonts and this issue appears only on some of them... A general solution would be nice.

# System Details Report
---

## Report details
- **Date generated:**                              2024-01-14 12:55:30

## Hardware Information:
- **Hardware Model:**                              ASUSTeK COMPUTER INC. VivoBook_ASUSLaptop X712DA_M712DA
- **Memory:**                                      12.0 GiB
- **Processor:**                                   AMD Ryzen™ 5 3500U with Radeon™ Vega Mobile Gfx × 8
- **Graphics:**                                    AMD Radeon™ Vega 8 Graphics
- **Disk Capacity:**                               512.1 GB

## Software Information:
- **Firmware Version:**                            X712DA.304
- **OS Name:**                                     Fedora Linux 39 (Workstation Edition)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.3
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.6.9-200.fc39.x86_64

**Comment by maniacx** [comment]
I will look into it. Thanks

**Comment by maniacx** [comment]
Hello @ionutbortis 
I have made some changes.
Can you try the updates version on Github.
You may have to install gettext if the installer script error out with msgfmt error
Test and Reply.

Also if  accessebility large-text is changed,  the popupmenu will rebuild avoiding ellipse or blank spaces.
However if display resolution, scalling resolution, fonts or themes are changed. You may have to restart the extension to display text propertly.

**Comment by ionutbortis** [comment]
Tested again with the latest code from here (revision a767e50) and everything looks fine on my end:
![Screenshot from 2024-01-15 11-47-02](https://github.com/maniacx/Bluetooth-Battery-Meter/assets/5013697/641f7629-f375-42b8-b033-6e62fa743f0a)

Tried out different resolutions, different scaling factors via Tweaks and different scales via Settings.

Thank you for fixing this!
